"""add_is_adhoc_to_chores

Revision ID: 9bd11299988c
Revises: 7b6389bfbc27
Create Date: 2026-02-07 16:26:01.498884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd11299988c'
down_revision = '7b6389bfbc27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('chores', sa.Column('is_adhoc', sa.Boolean(), nullable=True))
    # Set default value for existing records
    op.execute('UPDATE chores SET is_adhoc = false WHERE is_adhoc IS NULL')
    # Now make it non-nullable
    op.alter_column('chores', 'is_adhoc', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'is_adhoc')
    # ### end Alembic commands ###
